# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eee5d7000260ecef1862c7796f0ed36f43b60d9f4fb445c40b65eb8a7a7578d0c6fbc0ad42cdec49904860ad94b55254f659c6e74314d1f886a6d461ecec3262

test:
  secret_key_base: 43dd9325dac1d0f503bb0d092bd5ae661bac3cfbe644f22e514fff4f0ce7db51fc8a5ecba91a54000f303edd427648ec9b96b2f64b9bbda8c8a696dc3f556e60

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
